/**
 * Project-M Backend Server
 * * Handles Express REST routes for room creation/validation and
 * Socket.io WebSocket connections for real-time chat, typing indicators,
 * and WebRTC signaling.
 */


// ==========================================
// 1. IMPORTS & SERVER SETUP
// ==========================================
const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const cors = require("cors");

const app = express();

// Allow Cross-Origin requests (essential for separating frontend/backend during dev)
app.use(cors());

const server = http.createServer(app);

// Initialize Socket.io with permissive CORS for tunneling (e.g., Ngrok/VS Code Ports)
const io = new Server(server, {
    cors: {
        origin: "*",
    },
});


// ==========================================
// 2. GLOBAL STATE MANAGEMENT
// ==========================================

/** @type {Set<string>} Rooms generated via API but not yet joined by the host */
const pendingRooms = new Set();

/** @type {Set<string>} Rooms that are currently active with at least one user */
const activeRooms = new Set();

/** @type {Map<string, NodeJS.Timeout>} Timers to permanently delete rooms when they empty out */
const emptyRoomTimers = new Map();


// ==========================================
// 3. REST API ROUTES
// ==========================================

/**
 * @route GET /check-room/:code
 * @description Validates a room code before a user attempts to join.
 * @returns {Object} JSON containing `exists` (boolean) and `isFull` (boolean)
 */

app.get("/check-room/:code", (req, res) => {
    const roomCode = req.params.code;
    const room = io.sockets.adapter.rooms.get(roomCode);

    if (room && room.size > 0) {
        res.json({ exists: true, isFull: room.size >= 2 });
    } else {
        res.json({ exists: false });
    }
});

app.get("/create-room", (req, res) => {
    const chars = "0123456789ABCDEF";
    let roomCode;
    let isUnique = false;

    // Generate codes until we find one that isn't currently active or pending
    while (!isUnique) {
        roomCode = "";
        for (let i=0; i < 4; i++) {
            roomCode += chars[Math.floor(Math.random() * 16)];
        }

        const existingRoom = io.sockets.adapter.rooms.get(roomCode);

        if (!existingRoom && !pendingRooms.has(roomCode)) {
            isUnique = true;
        }
    }

    // Temporarily lock this room code so no one else generates it
    pendingRooms.add(roomCode);

    // Automatically release the lock after 3 seconds if the host fails to join
    setTimeout(() => {
        pendingRooms.delete(roomCode);
    }, 3000);

    res.json({ code: roomCode });
})

// ==========================================
// 4. WEBSOCKET (SOCKET.IO) EVENTS
// ==========================================

io.on("connection", (socket) => {

    /**
     * ROOM MANAGEMENT
     * Handles users joining rooms, upgrading room states from pending to active, 
     * and enforcing the 2-user limit.
     */

    socket.on("join-room", (data) => {
        // 1. DEFENSIVE GUARD: Ensure data is an object and roomCode is a string
        if (!data || typeof data.roomCode !== "string") {
            console.warn(`[SECURITY] Blocked invalid join-room from ${socket.id}`);
            return;
        }

        const { roomCode, create, username } = data;
        const room = io.sockets.adapter.rooms.get(roomCode);
        
        // Fallback username to prevent undefined crashes on the frontend
        socket.username = username || "Anonymous"; 

        // 2. STRICT ROOM CREATION VS JOINING LOGIC
        if (create) {
            // If they are creating, the room MUST have been generated by the API (pendingRooms)
            // or already be active (e.g., they hit refresh).
            if (!pendingRooms.has(roomCode) && !activeRooms.has(roomCode)) {
                socket.emit("room-not-found");
                return;
            }
            // Upgrade from pending to active
            pendingRooms.delete(roomCode);
            activeRooms.add(roomCode);
        } else {
            // If they are strictly joining, the room MUST already be fully active
            if (!activeRooms.has(roomCode)) {
                socket.emit("room-not-found");
                return;
            }
        }

        // If the room was empty and scheduled for deletion, cancel the deletion!
        if (emptyRoomTimers.has(roomCode)) {
            clearTimeout(emptyRoomTimers.get(roomCode));
            emptyRoomTimers.delete(roomCode);
        }

        const roomSize = room ? room.size : 0;

        // Enforce the strict 2-peer WebRTC limit
        if (roomSize >= 2 ) {
            socket.emit("room-full");
            return;
        }
        
        // Formally join the socket room
        socket.join(roomCode);

        // Notify the OTHER person in the room that someone arrived
        socket.to(roomCode).emit("user-connected", socket.username);

        // Broadcast the updated user count to everyone in the room
        const updatedRoom = io.sockets.adapter.rooms.get(roomCode);
        io.to(roomCode).emit("room-status", {
            users: updatedRoom.size
        });
    });

    /**
     * REAL-TIME CHAT & UI SIGNALING
     * Passes text messages and typing indicators between users.
     */
    socket.on("send-message", (data) => {
        // 1. DEFENSIVE GUARD: Does the payload exist?
        if (!data || !data.room || !data.message) {
            console.warn(`[SECURITY] Blocked malformed message payload from ${socket.id}`);
            return; 
        }

        // 2. SERVER AUTHORITY: Is the text actually a string?
        if (typeof data.message.text !== "string") {
            console.warn(`[SECURITY] Blocked non-string message from ${socket.id}`);
            return;
        }

        // If it passes, it is safe to broadcast to EVERYONE in the room (including sender)
        io.to(data.room).emit("receive-message", data.message);
    });

    socket.on("typing", ({ room, username }) => {
        socket.to(room).emit("user-typing", username);
    });

    socket.on("stop-typing", (room) => {
        socket.to(room).emit("user-stop-typing");
    });

    /**
     * WEBRTC SIGNALING (THE P2P HANDSHAKE)
     * These events act as a middleman to exchange WebRTC connection data 
     * between the two browsers so they can establish a direct Peer-to-Peer link.
     */
    socket.on("webrtc-offer", ({room,offer}) => {
        socket.to(room).emit("webrtc-offer", offer);
    });

    socket.on("webrtc-answer",({room,answer}) => {
        socket.to(room).emit("webrtc-answer", answer);
    });

    socket.on("webrtc-ice-candidate",({room,candidate}) => {
        socket.to(room).emit("webrtc-ice-candidate", candidate);
    });
    
    /**
     * DISCONNECTION HANDLING
     * Cleans up the room, notifies remaining users, and sets a self-destruct 
     * timer if the room becomes completely empty.
     */
    socket.on("disconnecting", () => {
        // A user can be in multiple rooms (default socket ID room + custom room)
        socket.rooms.forEach((roomCode) => {
            if (roomCode !== socket.id) {
                // Tell the remaining user that their peer left
                socket.to(roomCode).emit("user-disconnected", socket.username);

                // Update the room headcount
                const roomData = io.sockets.adapter.rooms.get(roomCode);
                const count = roomData ? roomData.size - 1 : 0;
                socket.to(roomCode).emit("room-status", {
                    users: count
                });

                // If the room is now completely empty, start the 5-second self-destruct timer
                if (count === 0 && activeRooms.has(roomCode)) {
                    const timer = setTimeout(() => {
                        activeRooms.delete(roomCode);
                        emptyRoomTimers.delete(roomCode);
                    }, 5000);

                    emptyRoomTimers.set(roomCode, timer);
                }
            }
        });
    });
});


// ==========================================
// 5. SERVER BOOTSTRAP
// ==========================================

// Listen on all network interfaces (0.0.0.0) to allow external tunneling
server.listen(5000, "0.0.0.0", () => {
    console.log("Server is running on port 5000");
});